### ISSUE TITLE
EDS Beta announced on library web platforms

### ISSUE THREAD

**Issue by crmcdonald** [culibraries/ses#3]
- [x] Finalize wording
- [x] Confirm more info article/page is ready for linking
- [x] Coordinate wording/timing with @nleboeuftrujillo (for Summon)
- [x] Create LibGuides box with information
- [x] Plan necessary changes to LibGuides templates to add box to all pages 
- [ ] Post notification / alert of EDS beta on 
> - [x] library website
> - [ ] libguides
> - [x] Summon

**Comment by crmcdonald** [comment]
Post notification / alert of EDS beta on 

- [ ] library website
- [ ] libguides
- [ ] Summon

**Comment by crmcdonald** [comment]
For website, see proposed approach on the test site - banner on [home page](https://www-test.colorado.edu/libraries/) and note added to search box on [all other pages](https://www-test.colorado.edu/libraries/services)

### Proposed wording for banner
**OneSearch is changing in Summer 2022**
We'll transition to a new search interface this summer. Learn more about [what you can expect](https://www-test.colorado.edu/libraries/library-services-platform-migration) (this will link to an EDS specific page or news article), or try out [the new search](https://discovery.ebsco.com/c/3czfwv/results) currently in beta.

### Below search box
OneSearch is [changing soon](https://www-test.colorado.edu/libraries/library-services-platform-migration) (this will link to EDS page/news)! [Try the beta site](http://discovery.ebsco.com/c/3czfwv/results)

**Comment by nleboeuftrujillo** [comment]
[Rough Draft of EDS specific page](https://docs.google.com/document/d/1X4A0HscnocqbLtdqb25lGEQWkjbXZb3mZDoDUc4h2ak/edit), place on [OneSearch page?](https://www.colorado.edu/libraries/research/find-articles-and-databases/onesearch)

**Comment by crmcdonald** [comment]
vendor dependent, but timeline is probably week of April 11

@nleboeuftrujillo is going to draft some more utility-oriented info for EDS, why we are doing this, how to get help, etc. that sort of thing. may end up working with comms to become a news story but we might also be able to put that information on [existing onesearch page](https://www.colorado.edu/libraries/research/find-articles-and-databases/onesearch) and keep everything together/benefit from good Google indexing

**Comment by crmcdonald** [comment]
@nleboeuftrujillo i did a bit more with the OneSearch page on our test site and I think this is easier to see. 
https://www-test.colorado.edu/libraries/research/find-articles-and-databases/onesearch

still pending information about who to contact for help with migrating links and any links to learn about new features. that can also potentially be edited out for starters and added back later.

**Comment by crmcdonald** [comment]
not putting a box in libguides for the summer - revisit later in the summer
